from __future__ import annotations

COMPONENT_SUGGEST = "suggest"
COMPONENT_FILTER = "filter"
COMPONENT_SERP = "serp"
COMPONENT_SELLERS = "sellers"

PIPELINE_DAILY = "daily"
PIPELINE_MONTHLY = "monthly"

RUN_STATUS_RUNNING = "running"
RUN_STATUS_SUCCESS = "success"
RUN_STATUS_PARTIAL = "partial"
RUN_STATUS_FAILED = "failed"
RUN_STATUS_NOT_READY = "not_ready"

TASK_STATUS_RUNNING = "running"
TASK_STATUS_SUCCESS = "success"
TASK_STATUS_PARTIAL = "partial"
TASK_STATUS_FAILED = "failed"
TASK_STATUS_NOT_READY = "not_ready"

ERROR_SEVERITY_CRITICAL = "critical"
ERROR_SEVERITY_NON_CRITICAL = "non_critical"

# Normalized error codes (post-V1)
ERROR_CODE_CONFIG_INVALID = "CFG_INVALID"
ERROR_CODE_RUN_LOCKED = "RUN_LOCKED"
ERROR_CODE_COMPONENT_NOT_READY = "COMP_NOT_READY"
ERROR_CODE_COMPONENT_NON_CRITICAL = "COMP_NON_CRITICAL"
ERROR_CODE_COMPONENT_CRITICAL = "COMP_CRITICAL"
ERROR_CODE_COMPONENT_UNHANDLED = "COMP_UNHANDLED"
ERROR_CODE_NETWORK = "NETWORK_ERROR"
ERROR_CODE_SCHEMA = "SCHEMA_ERROR"
ERROR_CODE_IO = "IO_ERROR"
ERROR_CODE_VALIDATION = "VALIDATION_ERROR"
ERROR_CODE_UNKNOWN = "UNKNOWN_ERROR"
